# _*_ coding: utf-8 _*_
# This code used to generated linux shell file.

'''
@author: Ruan Yang
Created on 2018.5.8
This code used to generated linux shell file.
'''

def ShellF(GAfilename,molname,nt):
	'''
	GAfilename : GaussianAntechamber.sh
	molname : molecule *.mol2 file name
	nt : how many nodes used to run gromacs
	'''
	with open('Streamline.sh','w') as f:
		f.write('#!/bin/bash \n')
		f.write('#$ -S /bin/sh\n')
		f.write('#$ -N test\n')
		f.write('#$ -j y\n')
		f.write('#$ -o .\n')
		f.write('#$ -e .\n')
		f.write('#$ -cwd\n')
		f.write('#$ -q all.q\n')
		f.write('#$ -masterq all.q@node9\n')
		f.write('#$ -pe thread 8-8\n')
		f.write('source ~/.bashrc\n')
		f.write('hash -r\n')
		f.write('export GMXBINPATH=/XXX/bin:GMXBINPATH\n')
		f.write('\n')
		for i in range(len(molname)):
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 1: Prepare GROMACS input configure and topology file."\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd %s\n'%(molname[i]))
			f.write('dos2unix *.sh *.in *.inp\n')
			f.write('mkdir ff\n')
			f.write('mkdir em\n')
			f.write('mkdir nvte\n')
			f.write('mkdir npte\n')
			f.write('mkdir nptpd\n')
			f.write('mkdir anneal\n')
			f.write('cp %s.sh %s.mol2 leap.in acpype.py *.inp ff\n'%(GAfilename,molname[i]))
			f.write('cd ff\n')
			f.write('chmod 700 %s.sh\n'%(GAfilename))
			f.write('nohup ./%s.sh &\n'%(GAfilename))
			f.write('wait\n')
			f.write('mv TST_GMX.top %s.top\n'%(molname[i]))
			f.write('cp %s_pack.pdb %s.top ../em\n'%(molname[i],molname[i]))
			f.write('cd ../\n')
			f.write(' \n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 2: Energy equlibrium"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd em\n')
			f.write('gmx grompp -f ../../emequilibrium.mdp -c %s_pack.pdb -p %s.top \
			-o emequilibrium.tpr -maxwarn 2\n'%(molname[i],molname[i]))
			f.write('gmx mdrun -nt %d -v -deffnm emequilibrium\n'%(nt))
			f.write('wait \n')
			f.write('cp emequilibrium.gro %s.top ../nvte\n'%(molname[i]))
			f.write('cd ../\n')
			f.write(' \n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 3: NVT equlibrium"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd nvte\n')
			f.write('gmx grompp -f ../../nvtequilibrium.mdp -c emequilibrium.gro -p %s.top\
			-o nvtequilibrium.tpr -maxwarn 2\n'%(molname[i]))
			f.write('gmx mdrun -nt %d -v -deffnm nvtequilibrium\n'%(nt))
			f.write('wait \n')
			f.write('cp nvtequilibrium.gro %s.top ../npte \n'%(molname[i]))
			f.write('cd ../\n')
			f.write(' \n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 4: NPT equlibrium"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd npte\n')
			f.write('gmx grompp -f ../../nptequilibrium.mdp -c nvtequilibrium.gro -p %s.top\
			-o nptequilibrium.tpr -maxwarn 2\n'%(molname[i]))
			f.write('gmx mdrun -nt %d -v -deffnm nptequilibrium\n'%(nt))
			f.write('wait \n')
			f.write('cp nptequilibrium.gro %s.top ../anneal \n'%(molname[i]))
			f.write('cp nptequilibrium.gro %s.top ../nptpd \n'%(molname[i]))
			f.write('cd ../\n')
			f.write('\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 5: NPT Producation run"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd nptpd\n')
			f.write('gmx grompp -f ../../nptpd.mdp -c nptequilibrium.gro -p %s.top \
			-o nptpd.tpr -maxwarn 2\n'%(molname[i]))
			f.write('gmx mdrun -nt %d -v -deffnm nptpd\n'%(nt))
			f.write('wait \n')
			f.write('cd ../\n')
			f.write('\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Step 6: Annealing Simulation"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('cd anneal\n')
			f.write('gmx grompp -f ../../anneal.mdp -c nptequilibrium.gro -p %s.top\
			-o anneal.tpr -maxwarn 2 \n'%(molname[i]))
			f.write('gmx mdrun -nt %d -v -deffnm anneal \n'%(nt))
			f.write('wait \n')
			f.write('cd ../\n')
			f.write('\n')
			f.write('cd ../\n')
			f.write(' \n')
	with open('analysis.sh','w') as f:
		f.write('#!/bin/bash \n')
		f.write('\n')
		f.write('# Analysis molecular basic properties.\n')
		f.write('# Reference: http://virtualchemistry.org/properties.php\n')
		f.write('# Liquid density ρ: https://en.wikipedia.org/wiki/Density\n')
		f.write('# Surface tension γ: https://en.wikipedia.org/wiki/Surface_tension\n')
		f.write('# Static dielectric constant ε0: https://en.wikipedia.org/wiki/Relative_permittivity\n')
		f.write('# Volumetric expansion coefficient αP: https://en.wikipedia.org/wiki/Thermal_expansion\n')
		f.write('# Isothermal compressibility κT: https://en.wikipedia.org/wiki/Compressibility\n')
		f.write('# Viscosity η: https://en.wikipedia.org/wiki/Viscosity\n')
		f.write('# Enthalpy of vaporization ΔHvap: https://en.wikipedia.org/wiki/Enthalpy_of_vaporization\n')
		f.write('# Standard Entropy S0: https://en.wikipedia.org/wiki/Standard_molar_entropy\n')
		f.write('# Heat capacity at constant volume CV: https://en.wikipedia.org/wiki/Heat_capacity\n')
		f.write('# Heat capacity at constant pressure CP: https://en.wikipedia.org/wiki/Heat_capacity\n')
		f.write('# Speed of sound cfluid: https://en.wikipedia.org/wiki/Speed_of_sound\n')
		f.write('\n')
		for i in range(len(molname)):
			f.write('cd %s/nptpd\n'%(molname[i]))
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Thermodynamic properties."\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write(' \n')
			f.write('mkdir Energy\n')
			f.write('cd Energy\n')
			f.write('seq 1 47 | gmx energy -f ../nptpd.edr -s ../nptpd.tpr -b 1000 -o %s_energy.xvg\n'%(molname[i]))
			f.write('cd ../\n')
			f.write(' \n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Analysis of motor ability"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('mkdir Msd\n')
			f.write('cd Msd\n')
			f.write('echo 0 | gmx msd -f ../nptpd.trr -s ../nptpd.tpr -o %s_msd.xvg -mol %s_mol.xvg -b 1000 \n'%(molname[i],molname[i]))
			f.write('cd ../\n')
			f.write(' \n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('echo "Dielectric constants"\n')
			f.write('echo "dipcorr.xvg:Dipole Autocorrelation Function"\n')
			f.write('echo "Mtot.xvg:Total dipole moment of the simulation box vs. time"\n')
			f.write('echo "epsilon: Epsilon and Kirkwood factors"\n')
			f.write('echo "#----------------------------------------------------------------#"\n')
			f.write('\n')
			f.write('mkdir Dielectric\n')
			f.write('cd Dielectric\n')
			f.write('echo 0 | gmx dipoles -f ../nptpd.trr -s ../nptpd.tpr -o %s_Mtot.xvg -c %s_dipcorr.xvg \
			-eps %s_epsilon.xvg -b 1000 -corr mol -P 2\n'%(molname[i],molname[i],molname[i]))
			f.write('cd ../')
			f.write(' \n')
			#f.write('echo "#----------------------------------------------------------------#"\n')
			#f.write('echo "Hydrogen bond analysis"\n')
			#f.write('echo "#----------------------------------------------------------------#"\n')
			#f.write('mkdir hbond\n')
			#f.write('cd hbond\n')
			#f.write('echo 0 | gmx hbond -s ../nptpd.tpr -f ../nptpd.trr -num %s_hb.xvg -ac %s_hbac.xvg -dist \
			#%s_hbdist.xvg -ang %s_hbang.xvg -life %s_hblife.xvg -b 1000 -a 30 -r 0.35 -temp 300\n'%(molname[i],\
			#molname[i],molname[i],molname[i],molname[i]))
			#f.write('cd ../')
			#f.write(' \n')
			#f.write('echo"#----------------------------------------------------------------#"\n')
			#f.write('echo "Calculate viscosities of liquids"\n')
			#f.write('echo"#----------------------------------------------------------------#"\n')
			#f.write('\n')
			#f.write('mkdir viscosities\n')
			#f.write('cd viscosities\n')
			#print('echo 0 | gmx tcaf -f ../nptpd.trr -s ../nptpd.tpr -ot %s_transcur.xvg -oa %s_tcaf_all.xvg\
			#-o %s_tcaf.xvg -of %s_tcaf_fit.xvg -oc %s_tcaf_cub.xvg -ov %s_visc_k.xvg -b 1000\n'(molname[i],molname[i],molname[i],\
			#molname[i],molname[i],molname[i]),file=f)
			#f.write('cd ../')
			#f.write('\n')
			f.write('cd ../\n')
			f.write('\n')
		pass
